export const SET_MARKER = 'SET_MARKER';

export const CLEAR_MARKERS = 'CLEAR_MARKERS';

export const LOAD_MARKERS = 'LOAD_MARKERS';

export const SAVE_MARKERS = 'SAVE_MARKERS';

export const SET_SAVED_MARKERS_AMOUNT = 'SET_SAVED_MARKERS_AMOUNT';

export const START_REQUEST_MARKERS = 'START_REQUEST_MARKERS';

export const END_REQUEST_MARKERS = 'END_REQUEST_MARKERS';

export const REQUEST_MARKERS_ERROR = 'REQUEST_MARKERS_ERROR';