export const SET_MARKER = 'SET_MARKER';

export const CLEAR_VISIBLE_MARKERS = 'CLEAR_VISIBLE_MARKERS';

export const CLEAR_SAVED_MARKERS = 'CLEAR_SAVED_MARKERS';

export const SET_VISIBLE_MARKERS = 'SET_VISIBLE_MARKERS';

export const SET_SAVED_MARKERS = 'SET_SAVED_MARKERS';

export const SET_SERVER_MARKERS_AMOUNT = 'SET_SERVER_MARKERS_AMOUNT';

export const START_REQUEST_MARKERS = 'START_REQUEST_MARKERS';

export const END_REQUEST_MARKERS = 'END_REQUEST_MARKERS';

export const REQUEST_MARKERS_ERROR = 'REQUEST_MARKERS_ERROR';
